updates

diff --git a/core/node/.scripts/symlink_user_core b/core/node/.scripts/symlink_user_core
--- a/core/node/.scripts/symlink_user_core
+++ b/core/node/.scripts/symlink_user_core
@@ -2,48 +2,30 @@
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
-# HELPER FUNCTIONS
-. "$DIR/helpers"
-
 # DEFINE COLORS
 YELLOW='\033[0;33m'
 GREEN='\033[0;32m'
 RED='\033[0;31m'
-BLUE='\033[0;94m'
-CYAN='\e[0;36m'
-MAGENTA='\033[0;35m'
 GRAY='\e[1;30m'
 WHITE='\e[33;97m'
 NC='\033[0m' # No Color
 
-function create_stubs() {
-  local user_node_core="$1"
+function parse_dep_aspect() {
+  local dep="$3"
+  local _dmt_dep_without_aspect=''
+  local _aspect=''
 
-  pkg_file="${user_node_core}/package.json"
+  arr=(${dep/\// }) # split on /
+  _aspect=''
+  if [ ${#arr[@]} == 1 ]; then
+    _dmt_dep_without_aspect="$arr"
+  else
+    _dmt_dep_without_aspect="${arr[@]:1}" # take everything except first el
+    _aspect="${arr[0]}"
+  fi
 
-if [ ! -f "$pkg_file" ]; then
-cat >"$pkg_file" <<EOL
-{
-  "type": "module"
-}
-EOL
-fi
-
-index_file="${user_node_core}/index.js"
-
-if [ ! -f "$index_file" ]; then
-cat >"$index_file" <<EOL
-import dmt from 'dmt/bridge';
-const { log } = dmt;
-
-function init(program) {
-  log.write('user core template init function called, see ~/.dmt/user/core/node/index.js');
-  log.write('read more: https://github.com/uniqpath/dmt/blob/master/help/USER_CORE_FRAMEWORK.md')
-}
-
-export default { init };
-EOL
-fi
+  eval "$1='${_dmt_dep_without_aspect}'"
+  eval "$2='${_aspect}'"
 }
 
 # deps from ~/.dmt/user/core/node/node_modules/[dep] to ~/.dmt/core/node/[aspect/dep]
@@ -55,35 +37,71 @@ declare -a DepList=(
 
 arg="$1"
 
-user_core="$DIR/../../../user/core"
-user_node_core="$user_core/node"
-user_node_modules="$user_node_core/node_modules"
+USER_CORE="$DIR/../../../user/core"
+USER_NODE_CORE="$USER_CORE/node"
+USER_DMT_MODULES="$USER_NODE_CORE/node_modules_helper"
 
-if [ -d "$user_core" ]; then
+if [ -d "$USER_CORE" ]; then
 
-  mkdir -p "$user_node_modules"
-  create_stubs "$user_node_core"
+  mkdir -p "$USER_DMT_MODULES"
 
-  for dep in "${DepList[@]}"; do
+  # remove all symlinks from $USER_DMT_MODULES
+  if [ "$arg" == "remove" ]; then
+    for deplink in "${USER_DMT_MODULES}"/*; do
+      if [ -L "$deplink" ]; then
+        rm $deplink
+      fi
+    done
+  else # create each dep symlink from $USER_DMT_MODULES
 
-    dmt_dep_without_aspect=''
-    aspect=''
-    parse_dep_aspect dmt_dep_without_aspect aspect "$dep"
+    # check package.json:
+    # - for existence
+    # - if package name is correct so that module imports work (dmt/bridge etc.) (new self-referential feature)
 
-    # todo: remove all symlinks, don't traverse the deps list
+    PKG_FILE="$USER_NODE_CORE/package.json"
 
-    # for now we have to use dmt- prefix here so that we import 'dmt-bridge' instead of 'bridge' (?)
-    # ah noo...
-    dep_symlink="${user_node_modules}/${dmt_dep_without_aspect}"
-    if [ "$arg" == "remove" ]; then
-      if [ -L "$dep_symlink" ]; then
-        rm "$dep_symlink"
+    if [ -f "$PKG_FILE" ]; then
+      LINE="\"name\": \"dmt\""
+      if ! grep -Fq "$LINE" "$PKG_FILE"; then
+        printf "⚠️  ${GRAY}SYMLINK_USER_CORE${NC} ${RED}Wrong package name in ${YELLOW}~/.dmt/user/core/node/package.json${NC} ${RED}— Correct name: ${WHITE}${LINE}${NC}\n"
       fi
     else
+      printf "⚠️  ${GRAY}SYMLINK_USER_CORE${NC} ${YELLOW}${PKG_FILE} is missing ...${NC}\n"
+    fi
+
+    # symlink each dep from ~/.dmt/user/core/node/node_modules_helper directory
+
+    for dep in "${DepList[@]}"; do
+      dmt_dep_without_aspect=''
+      aspect=''
+      parse_dep_aspect dmt_dep_without_aspect aspect "$dep"
+
+      dep_symlink="${USER_DMT_MODULES}/${dmt_dep_without_aspect}"
+
       if [ ! -L "$dep_symlink" ]; then
         ln -s "../../../../core/node/${dep}" "$dep_symlink"
       fi
-    fi
-  done
+    done
 
+    # check for self-reference entries in package.json for each dep
+
+    for dep in "${DepList[@]}"; do
+      dmt_dep_without_aspect=''
+      aspect=''
+      parse_dep_aspect dmt_dep_without_aspect aspect "$dep"
+
+      if [ -f "$PKG_FILE" ]; then
+        LINE="\"./${dmt_dep_without_aspect}\": \"./node_modules_helper/${dmt_dep_without_aspect}\""
+
+        if ! grep -Fq "$LINE" "$PKG_FILE"; then
+          printf "⚠️  ${GRAY}SYMLINK_USER_CORE${NC} ${RED}Module reference missing in ${YELLOW}~/.dmt/user/core/node/package.json ${RED}under ${YELLOW}\"exports\"${RED} key: ${NC}\n"
+          printf "${WHITE}\"exports\": {${NC}\n"
+          printf "${WHITE}  ...${NC}\n"
+          printf "${WHITE}  ${LINE}${NC}\n"
+          printf "${WHITE}  ...${NC}\n"
+          printf "${WHITE}}${NC}\n\n"
+        fi
+      fi
+    done
+  fi
 fi
